### ISSUE TITLE
Wrong npm package name

### ISSUE THREAD

**Issue by irrvrsl** [alexmngn/react-feedback-form#1]
Hello there! I read your article about structuring react & redux apps and wanted to see your example project. I cloned your repo and stucked on `npm install`. NPM package name is invalid, should be something like 'feedback-form' instead of 'Feedback form'. Thanks for your article. Best regards!

**Comment by alexghi** [comment]
That's true. You can change it in package.json until someone will change it in the code from the repo

**Comment by sethbergman** [comment]
It looks like this issue is resolved. Nice app @alexmngn !
